services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3000"
    volumes:
      - ./backend:/app
      - ./database:/database
    working_dir: /app
    command: "zig build -Doptimize=ReleaseSafe run"
    networks:
      - app-network
 
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend:/usr/share/nginx/html
      - /etc/letsencrypt/live/zant-hub.com:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge