name: Deploy to Production
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ZANT_HUB_HOST }}
          username: ${{ secrets.ZANT_HUB_USERNAME }}
          password: ${{ secrets.ZANT_HUB_PASSWORD }}
          port: 22
          script: |
            cd /home/docker/
            git clone https://github.com/ZantFoundation/Z-Ant-Server/
            cd /home/docker/Z-Ant-Server
            git fetch && git pull origin main
            # Stop existing containers and prune unused ones
            docker-compose down
            docker system prune -f
            # Build and start containers
            COMPOSE_BAKE=true docker-compose up --build --detach
